import productTop10_01 from '../../assets/homeImage/productTop10/productTop10_01.png';

export const productData = [
  {
    id: 1,
    name: '日本eSIM【Docomo】4G高速無限吃到飽(3~30天)',
    image: productTop10_01,
    price: 1200,
    originalPrice: 1500,
    warning: 'Google Pixel & OPPO 手機不適用',
    tag: '特價',
  },
  {
    id: 2,
    name: '商品名稱 2',
    image: productTop10_01,
    price: 980,
    originalPrice: 1200,
    warning: 'Google Pixel & OPPO 手機不適用',
    tag: '8折',
  },
  {
    id: 3,
    name: '商品名稱 3',
    image: productTop10_01,
    price: 1500,
    originalPrice: 1800,
    warning: 'Google Pixel & OPPO 手機不適用',
    tag: '優惠',
  },
  {
    id: 4,
    name: '商品名稱 4',
    image: productTop10_01,
    price: 2000,
    originalPrice: 2500,
    warning: 'Google Pixel & OPPO 手機不適用',
    tag: '折扣',
  },
  {
    id: 5,
    name: '商品名稱 5',
    image: productTop10_01,
    price: 1300,
    originalPrice: 1600,
    warning: 'Google Pixel & OPPO 手機不適用',
    tag: '熱門',
  },
  {
    id: 6,
    name: '商品名稱 6',
    image: productTop10_01,
    price: 900,
    originalPrice: 1100,
    warning: 'Google Pixel & OPPO 手機不適用',
    tag: '限量',
  },
  {
    id: 7,
    name: '商品名稱 7',
    image: productTop10_01,
    price: 1700,
    originalPrice: 2000,
    warning: 'Google Pixel & OPPO 手機不適用',
    tag: '新品',
  },
  {
    id: 8,
    name: '商品名稱 8',
    image: productTop10_01,
    price: 1100,
    originalPrice: 1400,
    warning: 'Google Pixel & OPPO 手機不適用',
    tag: '促銷',
  },
  {
    id: 9,
    name: '商品名稱 9',
    image: productTop10_01,
    price: 850,
    originalPrice: 1000,
    warning: 'Google Pixel & OPPO 手機不適用',
    tag: '特賣',
  },
  {
    id: 10,
    name: '商品名稱 10',
    image: productTop10_01,
    price: 1600,
    originalPrice: 1900,
    warning: 'Google Pixel & OPPO 手機不適用',
    tag: '人氣',
  },
];
